GET http://localhost:8000/api/persons


###
GET http://localhost:8000/api/persons/b16060b5-c11b-46b2-92be-ca75fa9820fc

###
POST http://localhost:8000/api/persons
Content-Type: application/json

{
    "firstName": "Duc1",
    "lastName": "Ngo1"
}

###
DELETE http://localhost:8000/api/persons/45175584-bfcc-48ec-b973-b2e2e90ab0261

###
PUT http://localhost:8000/api/persons/ba39d1ce-a7be-430e-b701-a0674ab7cc6e1
Content-Type: application/json

{
    "firstName": "Duc",
    "lastName": "Ngo"
}
